[2023-10-27 14:16:00,516] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:16:00,526] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:16:00,526] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:16:00,527] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:16:00,527] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:16:00,543] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 14:16:00,552] {standard_task_runner.py:52} INFO - Started process 16987 to run task
[2023-10-27 14:16:00,577] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpoucv_pz_', '--error-file', '/tmp/tmpxxu0x2j4']
[2023-10-27 14:16:00,578] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 14:16:00,627] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:16:00,681] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 14:16:01,404] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/gabriel/Documents/project_finance/datalake/stocks/AAPL'
[2023-10-27 14:16:01,412] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T171600, end_date=20231027T171601
[2023-10-27 14:16:01,421] {standard_task_runner.py:92} ERROR - Failed to execute job 5 for task AAPL (Cannot save file into a non-existent directory: '/home/gabriel/Documents/project_finance/datalake/stocks/AAPL'; 16987)
[2023-10-27 14:16:01,452] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 14:16:01,466] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:28:43,317] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:28:43,341] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:28:43,341] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:28:43,341] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:28:43,341] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:28:43,523] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 14:28:43,529] {standard_task_runner.py:52} INFO - Started process 19380 to run task
[2023-10-27 14:28:43,535] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpoi05b7r_', '--error-file', '/tmp/tmp16f5_6tn']
[2023-10-27 14:28:43,536] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 14:28:43,629] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:28:43,858] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 14:28:44,343] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 20, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/AAPL_20231003.csv'
[2023-10-27 14:28:44,364] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T172843, end_date=20231027T172844
[2023-10-27 14:28:44,402] {standard_task_runner.py:92} ERROR - Failed to execute job 5 for task AAPL ([Errno 13] Permission denied: '/AAPL_20231003.csv'; 19380)
[2023-10-27 14:28:44,442] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 14:28:44,471] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:32:59,899] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:32:59,915] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:32:59,915] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:32:59,915] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:32:59,915] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:32:59,936] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 14:32:59,939] {standard_task_runner.py:52} INFO - Started process 20374 to run task
[2023-10-27 14:32:59,943] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpuwxc53un', '--error-file', '/tmp/tmptihls9ba']
[2023-10-27 14:32:59,944] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 14:32:59,985] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:33:00,040] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 14:33:00,527] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 14:33:00,540] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T173259, end_date=20231027T173300
[2023-10-27 14:33:00,606] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 14:33:00,627] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:53:15,592] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:53:15,598] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 14:53:15,598] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:53:15,598] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:53:15,598] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:53:15,608] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 14:53:15,612] {standard_task_runner.py:52} INFO - Started process 23074 to run task
[2023-10-27 14:53:15,616] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpqfazszaj', '--error-file', '/tmp/tmpt6j9bfgn']
[2023-10-27 14:53:15,617] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 14:53:15,669] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:53:15,729] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 14:53:16,305] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 14:53:16,314] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T175315, end_date=20231027T175316
[2023-10-27 14:53:16,337] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 14:53:16,425] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 15:22:38,301] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 15:22:38,307] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 15:22:38,307] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 15:22:38,307] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 15:22:38,307] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 15:22:38,330] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 15:22:38,335] {standard_task_runner.py:52} INFO - Started process 26929 to run task
[2023-10-27 15:22:38,338] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpqwe8kml9', '--error-file', '/tmp/tmpn0bpsvx7']
[2023-10-27 15:22:38,338] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 15:22:38,388] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 15:22:38,567] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 15:22:39,146] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 15:22:39,158] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T182238, end_date=20231027T182239
[2023-10-27 15:22:39,180] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 15:22:39,203] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 17:00:48,987] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 17:00:48,994] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 17:00:48,994] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:00:48,994] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 17:00:48,994] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:00:49,024] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 17:00:49,028] {standard_task_runner.py:52} INFO - Started process 39106 to run task
[2023-10-27 17:00:49,031] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmp2utova5y', '--error-file', '/tmp/tmpntod0cve']
[2023-10-27 17:00:49,032] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 17:00:49,127] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 17:00:49,253] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 17:00:49,717] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 20, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/home/gabriel/Documents/project_finance/datalake/Bronze/stocks/AAPL'
[2023-10-27 17:00:49,731] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T200048, end_date=20231027T200049
[2023-10-27 17:00:49,747] {standard_task_runner.py:92} ERROR - Failed to execute job 5 for task AAPL ([Errno 21] Is a directory: '/home/gabriel/Documents/project_finance/datalake/Bronze/stocks/AAPL'; 39106)
[2023-10-27 17:00:49,772] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 17:00:49,788] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 17:08:00,553] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 17:08:00,559] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 17:08:00,559] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:08:00,559] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 17:08:00,559] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:08:00,568] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 17:08:00,573] {standard_task_runner.py:52} INFO - Started process 40773 to run task
[2023-10-27 17:08:00,577] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpgvt8dwry', '--error-file', '/tmp/tmptbfma88i']
[2023-10-27 17:08:00,577] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 17:08:00,616] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 17:08:00,666] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 17:08:01,290] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 17:08:01,316] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T200800, end_date=20231027T200801
[2023-10-27 17:08:01,513] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 17:08:01,530] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 18:08:58,629] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 18:08:58,634] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [queued]>
[2023-10-27 18:08:58,635] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 18:08:58,635] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 18:08:58,635] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 18:08:58,652] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-03 00:00:00+00:00
[2023-10-27 18:08:58,660] {standard_task_runner.py:52} INFO - Started process 48816 to run task
[2023-10-27 18:08:58,665] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpkm26dfvz', '--error-file', '/tmp/tmpk39zlret']
[2023-10-27 18:08:58,666] {standard_task_runner.py:80} INFO - Job 5: Subtask AAPL
[2023-10-27 18:08:58,720] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-03T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 18:08:58,773] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-03T00:00:00+00:00
[2023-10-27 18:08:59,399] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 18:08:59,406] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231003T000000, start_date=20231027T210858, end_date=20231027T210859
[2023-10-27 18:08:59,465] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 18:08:59,569] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
