[2023-10-27 14:16:57,463] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:16:57,473] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:16:57,473] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:16:57,473] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:16:57,473] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:16:57,490] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 14:16:57,500] {standard_task_runner.py:52} INFO - Started process 17396 to run task
[2023-10-27 14:16:57,504] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmplglfjsyj', '--error-file', '/tmp/tmp5_vpjxqe']
[2023-10-27 14:16:57,505] {standard_task_runner.py:80} INFO - Job 25: Subtask AAPL
[2023-10-27 14:16:57,554] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:16:57,613] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 14:16:58,222] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/gabriel/Documents/project_finance/datalake/stocks/AAPL'
[2023-10-27 14:16:58,227] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T171657, end_date=20231027T171658
[2023-10-27 14:16:58,237] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task AAPL (Cannot save file into a non-existent directory: '/home/gabriel/Documents/project_finance/datalake/stocks/AAPL'; 17396)
[2023-10-27 14:16:58,260] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 14:16:58,277] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:30:23,564] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:30:23,606] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:30:23,606] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:30:23,606] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:30:23,606] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:30:23,667] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 14:30:23,682] {standard_task_runner.py:52} INFO - Started process 19747 to run task
[2023-10-27 14:30:23,691] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmp7uqlzvyp', '--error-file', '/tmp/tmp6xcy9md1']
[2023-10-27 14:30:23,693] {standard_task_runner.py:80} INFO - Job 25: Subtask AAPL
[2023-10-27 14:30:23,771] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:30:23,898] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 14:30:24,849] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 20, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/AAPL_20231010.csv'
[2023-10-27 14:30:24,856] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T173023, end_date=20231027T173024
[2023-10-27 14:30:24,868] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task AAPL ([Errno 13] Permission denied: '/AAPL_20231010.csv'; 19747)
[2023-10-27 14:30:24,914] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 14:30:24,943] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:34:12,246] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:34:12,256] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:34:12,256] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:34:12,257] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:34:12,257] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:34:12,271] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 14:34:12,276] {standard_task_runner.py:52} INFO - Started process 20704 to run task
[2023-10-27 14:34:12,285] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpl5v9n9r4', '--error-file', '/tmp/tmpp2aabize']
[2023-10-27 14:34:12,286] {standard_task_runner.py:80} INFO - Job 25: Subtask AAPL
[2023-10-27 14:34:12,349] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:34:12,437] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 14:34:13,055] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 14:34:13,101] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T173412, end_date=20231027T173413
[2023-10-27 14:34:13,252] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 14:34:13,281] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:54:21,860] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:54:21,871] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 14:54:21,871] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:54:21,871] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:54:21,871] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:54:21,896] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 14:54:21,903] {standard_task_runner.py:52} INFO - Started process 23396 to run task
[2023-10-27 14:54:21,923] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmp4rzpwr6c', '--error-file', '/tmp/tmp_rmjfg4f']
[2023-10-27 14:54:21,925] {standard_task_runner.py:80} INFO - Job 25: Subtask AAPL
[2023-10-27 14:54:22,145] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:54:22,226] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 14:54:23,009] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 14:54:23,015] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T175421, end_date=20231027T175423
[2023-10-27 14:54:23,043] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 14:54:23,057] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 15:23:34,716] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 15:23:34,723] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 15:23:34,723] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 15:23:34,723] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 15:23:34,723] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 15:23:34,733] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 15:23:34,736] {standard_task_runner.py:52} INFO - Started process 27250 to run task
[2023-10-27 15:23:34,740] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpnu1tx56o', '--error-file', '/tmp/tmpfs_9gld0']
[2023-10-27 15:23:34,740] {standard_task_runner.py:80} INFO - Job 25: Subtask AAPL
[2023-10-27 15:23:34,778] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 15:23:34,821] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 15:23:35,256] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 15:23:35,278] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T182334, end_date=20231027T182335
[2023-10-27 15:23:35,323] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 15:23:35,341] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 17:02:03,443] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 17:02:03,483] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 17:02:03,486] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:02:03,486] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 17:02:03,487] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:02:03,554] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 17:02:03,557] {standard_task_runner.py:52} INFO - Started process 39470 to run task
[2023-10-27 17:02:03,560] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpm77gnm2k', '--error-file', '/tmp/tmpao71w4dv']
[2023-10-27 17:02:03,561] {standard_task_runner.py:80} INFO - Job 30: Subtask AAPL
[2023-10-27 17:02:03,592] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 17:02:03,630] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 17:02:04,067] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 20, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/home/gabriel/Documents/project_finance/datalake/Bronze/stocks/AAPL'
[2023-10-27 17:02:04,073] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T200203, end_date=20231027T200204
[2023-10-27 17:02:04,084] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task AAPL ([Errno 21] Is a directory: '/home/gabriel/Documents/project_finance/datalake/Bronze/stocks/AAPL'; 39470)
[2023-10-27 17:02:04,097] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 17:02:04,115] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 17:09:19,625] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 17:09:19,631] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 17:09:19,632] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:09:19,632] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 17:09:19,632] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:09:19,642] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 17:09:19,646] {standard_task_runner.py:52} INFO - Started process 41186 to run task
[2023-10-27 17:09:19,651] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmp7jz574lp', '--error-file', '/tmp/tmpry24ssc9']
[2023-10-27 17:09:19,652] {standard_task_runner.py:80} INFO - Job 30: Subtask AAPL
[2023-10-27 17:09:19,693] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 17:09:19,759] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 17:09:20,269] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 17:09:20,277] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T200919, end_date=20231027T200920
[2023-10-27 17:09:20,360] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 17:09:20,464] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 18:10:15,040] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 18:10:15,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [queued]>
[2023-10-27 18:10:15,049] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 18:10:15,049] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 18:10:15,049] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 18:10:15,058] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): AAPL> on 2023-10-10 00:00:00+00:00
[2023-10-27 18:10:15,062] {standard_task_runner.py:52} INFO - Started process 49317 to run task
[2023-10-27 18:10:15,077] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'AAPL', 'scheduled__2023-10-10T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmp1xj37dyb', '--error-file', '/tmp/tmpqgy41vow']
[2023-10-27 18:10:15,078] {standard_task_runner.py:80} INFO - Job 29: Subtask AAPL
[2023-10-27 18:10:15,137] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.AAPL scheduled__2023-10-10T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 18:10:15,220] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=AAPL
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-10T00:00:00+00:00
[2023-10-27 18:10:15,800] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 18:10:15,842] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=AAPL, execution_date=20231010T000000, start_date=20231027T211015, end_date=20231027T211015
[2023-10-27 18:10:15,897] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 18:10:15,974] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
