[2023-10-27 14:17:27,848] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:17:27,854] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:17:27,854] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:17:27,854] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:17:27,854] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:17:27,866] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 14:17:27,869] {standard_task_runner.py:52} INFO - Started process 17577 to run task
[2023-10-27 14:17:27,872] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmp9gpg7haf', '--error-file', '/tmp/tmphwx9af2y']
[2023-10-27 14:17:27,873] {standard_task_runner.py:80} INFO - Job 35: Subtask GOOG
[2023-10-27 14:17:27,919] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:17:27,977] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 14:17:28,379] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/gabriel/Documents/project_finance/datalake/stocks/GOOG'
[2023-10-27 14:17:28,394] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T171727, end_date=20231027T171728
[2023-10-27 14:17:28,405] {standard_task_runner.py:92} ERROR - Failed to execute job 35 for task GOOG (Cannot save file into a non-existent directory: '/home/gabriel/Documents/project_finance/datalake/stocks/GOOG'; 17577)
[2023-10-27 14:17:28,429] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 14:17:28,444] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:31:06,559] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:31:06,591] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:31:06,605] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:31:06,606] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:31:06,606] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:31:06,633] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 14:31:06,647] {standard_task_runner.py:52} INFO - Started process 19893 to run task
[2023-10-27 14:31:06,651] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmppo95tjck', '--error-file', '/tmp/tmp0c9sutfv']
[2023-10-27 14:31:06,651] {standard_task_runner.py:80} INFO - Job 35: Subtask GOOG
[2023-10-27 14:31:06,743] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:31:06,828] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 14:31:07,466] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 20, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/GOOG_20231012.csv'
[2023-10-27 14:31:07,494] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T173106, end_date=20231027T173107
[2023-10-27 14:31:07,516] {standard_task_runner.py:92} ERROR - Failed to execute job 35 for task GOOG ([Errno 13] Permission denied: '/GOOG_20231012.csv'; 19893)
[2023-10-27 14:31:07,564] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 14:31:07,632] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:35:01,661] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:35:01,680] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:35:01,680] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:35:01,681] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:35:01,681] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:35:01,708] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 14:35:01,715] {standard_task_runner.py:52} INFO - Started process 20870 to run task
[2023-10-27 14:35:01,725] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmplmpme549', '--error-file', '/tmp/tmprp491tyg']
[2023-10-27 14:35:01,727] {standard_task_runner.py:80} INFO - Job 35: Subtask GOOG
[2023-10-27 14:35:01,804] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:35:01,985] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 14:35:02,540] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 14:35:02,551] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T173501, end_date=20231027T173502
[2023-10-27 14:35:02,611] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 14:35:02,637] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 14:54:52,634] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:54:52,640] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 14:54:52,641] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:54:52,641] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 14:54:52,641] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 14:54:52,653] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 14:54:52,658] {standard_task_runner.py:52} INFO - Started process 23544 to run task
[2023-10-27 14:54:52,661] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpg5r7a8dy', '--error-file', '/tmp/tmp7d60rqer']
[2023-10-27 14:54:52,663] {standard_task_runner.py:80} INFO - Job 35: Subtask GOOG
[2023-10-27 14:54:52,705] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 14:54:52,921] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 14:54:53,405] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 14:54:53,410] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T175452, end_date=20231027T175453
[2023-10-27 14:54:53,457] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 14:54:53,471] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 15:24:04,941] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 15:24:04,950] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 15:24:04,950] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 15:24:04,950] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 15:24:04,951] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 15:24:04,964] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 15:24:04,969] {standard_task_runner.py:52} INFO - Started process 27394 to run task
[2023-10-27 15:24:04,974] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpi4pno122', '--error-file', '/tmp/tmpw_3z30ql']
[2023-10-27 15:24:04,975] {standard_task_runner.py:80} INFO - Job 35: Subtask GOOG
[2023-10-27 15:24:05,012] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 15:24:05,074] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 15:24:05,481] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 15:24:05,487] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T182404, end_date=20231027T182405
[2023-10-27 15:24:05,527] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 15:24:05,543] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 17:02:36,691] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 17:02:36,698] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 17:02:36,698] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:02:36,699] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 17:02:36,699] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:02:36,721] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 17:02:36,725] {standard_task_runner.py:52} INFO - Started process 39635 to run task
[2023-10-27 17:02:36,730] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmp5oox3ydz', '--error-file', '/tmp/tmplkqdpvx9']
[2023-10-27 17:02:36,731] {standard_task_runner.py:80} INFO - Job 42: Subtask GOOG
[2023-10-27 17:02:36,781] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 17:02:36,836] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 17:02:37,246] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabriel/Documents/project_finance/airflow/dags/get_finance.py", line 20, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/gabriel/Documents/project_finance/venv/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/home/gabriel/Documents/project_finance/datalake/Bronze/stocks/GOOG'
[2023-10-27 17:02:37,252] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T200236, end_date=20231027T200237
[2023-10-27 17:02:37,264] {standard_task_runner.py:92} ERROR - Failed to execute job 42 for task GOOG ([Errno 21] Is a directory: '/home/gabriel/Documents/project_finance/datalake/Bronze/stocks/GOOG'; 39635)
[2023-10-27 17:02:37,279] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-27 17:02:37,298] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 17:09:53,107] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 17:09:53,114] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 17:09:53,115] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:09:53,115] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 17:09:53,115] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 17:09:53,131] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 17:09:53,135] {standard_task_runner.py:52} INFO - Started process 41360 to run task
[2023-10-27 17:09:53,139] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpvi9xyuo3', '--error-file', '/tmp/tmpufm4vme7']
[2023-10-27 17:09:53,140] {standard_task_runner.py:80} INFO - Job 42: Subtask GOOG
[2023-10-27 17:09:53,174] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 17:09:53,220] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 17:09:54,009] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 17:09:54,015] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T200953, end_date=20231027T200954
[2023-10-27 17:09:54,030] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 17:09:54,045] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-27 18:10:50,697] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 18:10:50,705] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-27 18:10:50,705] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 18:10:50,705] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-27 18:10:50,706] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-27 18:10:50,718] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2023-10-12 00:00:00+00:00
[2023-10-27 18:10:50,728] {standard_task_runner.py:52} INFO - Started process 49535 to run task
[2023-10-27 18:10:50,731] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/get_finance.py', '--cfg-path', '/tmp/tmpoaeo4vr4', '--error-file', '/tmp/tmpk_us25vk']
[2023-10-27 18:10:50,732] {standard_task_runner.py:80} INFO - Job 42: Subtask GOOG
[2023-10-27 18:10:50,909] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2023-10-12T00:00:00+00:00 [running]> on host airflow-virtual-machine
[2023-10-27 18:10:50,954] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-27 18:10:51,360] {python.py:173} INFO - Done. Returned value was: None
[2023-10-27 18:10:51,366] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20231012T000000, start_date=20231027T211050, end_date=20231027T211051
[2023-10-27 18:10:51,388] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-27 18:10:51,407] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
